#!/bin/sh

# Everything about this makes me feel dirty
crontab -l | /usr/xpg4/bin/grep -qs etch
if [ $? != 0 ]
then
	crontab -l > /tmp/root_crontab || exit 1
	echo "0 * * * * /usr/sbin/etch_cron_wrapper" >> /tmp/root_crontab || exit 1
	crontab /tmp/root_crontab
	rm /tmp/root_crontab
fi

