#!/usr/bin/ruby

# We don't use NTP on VMware virtualized hosts per VMware's
# recommendation

if @facts['manufacturer'] !~ /^VMware/
  if @groups.include?('ntp-server')
    @contents = IO.read('ntp.conf.server')
  else
    @contents = IO.read('ntp.conf.client')
  end

  # Add OS-specific bits
  if @facts['operatingsystem'] == 'Solaris'
    @contents << IO.read('ntp.conf.solaris')
  else
    abort "Unsupported OS #{@facts['operatingsystem']}"
  end
end

